webnode/companyWeb/urls.py
from django.urls import path
from companyWeb import views


app_name = 'companyWeb'
urlpatterns = [
    path('',views.companyWeb,name = 'companyWeb'),
]

webnode/main/urls.py
from django.urls import path
from main import views


app_name = 'main'
urlpatterns = [
    path('',views.main,name = 'main'),
]

webnode/networkShop/urls.py
from django.urls import path
from networkShop import views


app_name = 'networkShop'
urlpatterns = [
    path('',views.networkShop,name = 'networkShop'),
]

webnode/personalWeb/urls.py
from django.urls import path
from personalWeb import views


app_name = 'personalWeb'
urlpatterns = [
    path('',views.personalWeb,name = 'personalWeb'),
]

webnode/webnode/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/',include('main.urls',namespace = 'main')),
    path('personalWeb/',include('personalWeb.urls',namespace = 'personalWeb')),
    path('companyWeb/',include('companyWeb.urls',namespace = 'companyWeb')),
    path('networkShop/',include('networkShop.urls',namespace = 'networkShop')),
    re_path('.*',views.main),
]

webnode/companyWeb/models.py
from django.db import models

# Create your models here.

webnode/main/models.py
from django.db import models

# Create your models here.

webnode/networkShop/models.py
from django.db import models

# Create your models here.

webnode/personalWeb/models.py
from django.db import models

# Create your models here.

webnode/companyWeb/views.py
from django.shortcuts import render

# Create your views here.
def companyWeb(request):
    return render(request,'companyWeb/companyWeb.html');

webnode/main/views.py
from django.shortcuts import render

# Create your views here.
def main(request):
    return render(request,'main/main.html')

webnode/networkShop/views.py
from django.shortcuts import render

# Create your views here.
def networkShop(request):
    return render(request,'networkShop/networkShop.html');

webnode/personalWeb/views.py
from django.shortcuts import render

# Create your views here.
def personalWeb(request):
    return render(request,'personalWeb/personalWeb.html');

webnode/companyWeb/templates/companyWeb/companyWeb.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>建立自己網站</title>
    <meta charset = 'utf-8'>
    <link rel='stylesheet' href='{% static "companyWeb/css/companyWeb1.css" %}'>
  </head>
  <body>
    <div id = wrapper>
      <header>
        <img id = 'webnode' src = '{% static "companyWeb/img/webnode.png" %}'>
        <ul>
          <li><a href = '{% url "main:main" %}'>首頁</a></li>
          <li><a href = '{% url "personalWeb:personalWeb" %}'>個人網站</a></li>
          <li><a href = '{% url "companyWeb:companyWeb" %}'>企業網站</a></li>
          <li><a href='{% url "networkShop:networkShop" %}'>網路商城</a></li>
        </ul>
      </header>
        <div id = 'content'>
          <img src = '{% static "companyWeb/img/circles.png" %}'>
          <h1>一群優秀的用戶將為繞著您</h1>
          <span>目前已經有超過 18,000,000 來自世界各地的公司企業、學生、藝術家和部落客等成為我們 Webnode 的滿意用戶。</span>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </body>
</html>

webnode/main/templates/main/main.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>建立自己網站</title>
    <meta charset = 'utf-8'>
    <link rel = 'stylesheet' href = '{% static "main/css/main.css" %}'>
   </head>
  <body>
    <div id = wrapper>
      <header>
        <img id = 'webnode' src = '{% static "main/img/webnode.png" %}'>
        <ul>
          <li><a href = '{% url "main:main" %}'>首頁</a></li>
          <li><a href = '{% url "personalWeb:personalWeb" %}'>個人網站</a></li>
          <li><a href = '{% url "companyWeb:companyWeb" %}'>企業網站</a></li>
          <li><a href='{% url "networkShop:networkShop" %}'>網路商城</a></li>
        </ul>
      </header>
      <div class = 'right marginTop1'>
        <span>現在時刻：</span>
        <span id= time></span>
      </div>
      <div id = 'content'>
        <div class = 'center marginTop5'>
          <p><strong>我們各種技術服務，協助您快速架設網站。</strong></p>
        </div>
      </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src = '{% static "main/js/main.js" %}'></script>
  </body>
</html>

webnode/networkShop/templates/networkShop/networkShop.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>建立自己網站</title>
    <meta charset = 'utf-8'>
    <link rel='stylesheet' href='{% static "networkShop/css/networkShop.css" %}'>
  </head>
  <body>
    <div id = wrapper>
      <header>
        <img id = 'webnode' src = '{% static "networkShop/img/webnode.png" %}'>
        <ul>
          <li><a href = '{% url "main:main" %}'>首頁</a></li>
          <li><a href = '{% url "personalWeb:personalWeb" %}'>個人網站</a></li>
          <li><a href = '{% url "companyWeb:companyWeb" %}'>企業網站</a></li>
          <li><a href='{% url "networkShop:networkShop" %}'>網路商城</a></li>
        </ul>
      </header>
        <div id = 'content'>
          <img src = '{% static "networkShop/img/globe.png" %}'>
          <h1>理想的網站及網路商城</h1>
          <span>上百種的新潮樣式，絕對能符合您個人需求，為您設立個人網站，公司企業網站以及創立網路商城的最佳選擇。</span>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </body>
</html>

webnode/personalWeb/templates/personalWeb/personalWeb.html
<!doctype html>
{% load staticfiles %}
<html>
  <head>
    <title>建立自己網站</title>
    <meta charset = 'utf-8'>
    <link rel='stylesheet' href='{% static "personalWeb/css/personalWeb.css" %}'>
  </head>
  <body>
    <div id = wrapper>
      <header>
        <img id = 'webnode' src = '{% static "personalWeb/img/webnode.png" %}'>
        <ul>
          <li><a href = '{% url "main:main" %}'>首頁</a></li>
          <li><a href = '{% url "personalWeb:personalWeb" %}'>個人網站</a></li>
          <li><a href = '{% url "companyWeb:companyWeb" %}'>企業網站</a></li>
          <li><a href='{% url "networkShop:networkShop" %}'>網路商城</a></li>
        </ul>
      </header>
        <div id = 'content'>
          <img src = '{% static "personalWeb/img/clock.png" %}'>
          <h1>免費又簡單的網站設立工具</h1>
          <span>一個快速且容易的網站設立工具，在網路上設計網站十分的簡單又免費。此外，您也可以使用自己的網域名稱。</span>
        </div>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </body>
</html>